/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.parser;

import Lyrics.lexer.*;
import Lyrics.node.*;
import Lyrics.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PArchivo node1 = (PArchivo) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AAarchivo1Archivo */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAarchivo2Archivo */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list, false);
            }
            break;
            case 2: /* reduce ALinea */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce AAtimestampcontenido1Contenido */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list, false);
            }
            break;
            case 4: /* reduce AAtimestampcontenido2Contenido */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list, false);
            }
            break;
            case 5: /* reduce AMetadatoContenido */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce ATerminal$Linea */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list, true);
            }
            break;
            case 7: /* reduce ANonTerminal$Linea */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AAarchivo1Archivo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PArchivo parchivoNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        }

        parchivoNode1 = new AArchivo(listNode2);
        }
	nodeList.add(parchivoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAarchivo2Archivo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArchivo parchivoNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        parchivoNode1 = new AArchivo(listNode3);
        }
	nodeList.add(parchivoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce ALinea */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLinea plineaNode1;
        {
            // Block
        TAbrecorchete tabrecorcheteNode2;
        PContenido pcontenidoNode3;
        tabrecorcheteNode2 = (TAbrecorchete)nodeArrayList1.get(0);
        pcontenidoNode3 = (PContenido)nodeArrayList2.get(0);

        plineaNode1 = new ALinea(tabrecorcheteNode2, pcontenidoNode3);
        }
	nodeList.add(plineaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAtimestampcontenido1Contenido */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContenido pcontenidoNode1;
        {
            // Block
        TNumeros tnumerosNode2;
        TDospuntos tdospuntosNode3;
        TNumeros tnumerosNode4;
        TPunto tpuntoNode5;
        TNumeros tnumerosNode6;
        TCierracorchete tcierracorcheteNode7;
        @SuppressWarnings("unused") Object nullNode8 = null;
        tnumerosNode2 = (TNumeros)nodeArrayList1.get(0);
        tdospuntosNode3 = (TDospuntos)nodeArrayList2.get(0);
        tnumerosNode4 = (TNumeros)nodeArrayList3.get(0);
        tpuntoNode5 = (TPunto)nodeArrayList4.get(0);
        tnumerosNode6 = (TNumeros)nodeArrayList5.get(0);
        tcierracorcheteNode7 = (TCierracorchete)nodeArrayList6.get(0);

        pcontenidoNode1 = new ATimestampContenido(tnumerosNode2, tdospuntosNode3, tnumerosNode4, tpuntoNode5, tnumerosNode6, tcierracorcheteNode7, null);
        }
	nodeList.add(pcontenidoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AAtimestampcontenido2Contenido */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContenido pcontenidoNode1;
        {
            // Block
        TNumeros tnumerosNode2;
        TDospuntos tdospuntosNode3;
        TNumeros tnumerosNode4;
        TPunto tpuntoNode5;
        TNumeros tnumerosNode6;
        TCierracorchete tcierracorcheteNode7;
        TTexto ttextoNode8;
        tnumerosNode2 = (TNumeros)nodeArrayList1.get(0);
        tdospuntosNode3 = (TDospuntos)nodeArrayList2.get(0);
        tnumerosNode4 = (TNumeros)nodeArrayList3.get(0);
        tpuntoNode5 = (TPunto)nodeArrayList4.get(0);
        tnumerosNode6 = (TNumeros)nodeArrayList5.get(0);
        tcierracorcheteNode7 = (TCierracorchete)nodeArrayList6.get(0);
        ttextoNode8 = (TTexto)nodeArrayList7.get(0);

        pcontenidoNode1 = new ATimestampContenido(tnumerosNode2, tdospuntosNode3, tnumerosNode4, tpuntoNode5, tnumerosNode6, tcierracorcheteNode7, ttextoNode8);
        }
	nodeList.add(pcontenidoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AMetadatoContenido */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContenido pcontenidoNode1;
        {
            // Block
        TTextolimitado ttextolimitadoNode2;
        TDospuntos tdospuntosNode3;
        TTexto ttextoNode4;
        TCierracorchete tcierracorcheteNode5;
        ttextolimitadoNode2 = (TTextolimitado)nodeArrayList1.get(0);
        tdospuntosNode3 = (TDospuntos)nodeArrayList2.get(0);
        ttextoNode4 = (TTexto)nodeArrayList3.get(0);
        tcierracorcheteNode5 = (TCierracorchete)nodeArrayList4.get(0);

        pcontenidoNode1 = new AMetadatoContenido(ttextolimitadoNode2, tdospuntosNode3, ttextoNode4, tcierracorcheteNode5);
        }
	nodeList.add(pcontenidoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce ATerminal$Linea */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PLinea plineaNode1;
        plineaNode1 = (PLinea)nodeArrayList1.get(0);
	if(plineaNode1 != null)
	{
	  listNode2.add(plineaNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce ANonTerminal$Linea */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PLinea plineaNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        plineaNode2 = (PLinea)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(plineaNode2 != null)
	{
	  listNode3.add(plineaNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {3, SHIFT, 1}, },
			{{-1, ERROR, 1}, {0, SHIFT, 5}, {2, SHIFT, 6}, },
			{{-1, ERROR, 2}, {7, ACCEPT, -1}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 1}, {3, SHIFT, 1}, },
			{{-1, ERROR, 5}, {6, SHIFT, 9}, },
			{{-1, ERROR, 6}, {6, SHIFT, 10}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 9}, {0, SHIFT, 11}, },
			{{-1, ERROR, 10}, {1, SHIFT, 12}, },
			{{-1, ERROR, 11}, {5, SHIFT, 13}, },
			{{-1, ERROR, 12}, {4, SHIFT, 14}, },
			{{-1, ERROR, 13}, {0, SHIFT, 15}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 15}, {4, SHIFT, 16}, },
			{{-1, REDUCE, 3}, {1, SHIFT, 17}, },
			{{-1, REDUCE, 4}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, {4, 8}, },
			{{-1, 7}, },
			{{-1, 4}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '[', EOF",
			"expecting: numeros, textolimitado",
			"expecting: EOF",
			"expecting: ':'",
			"expecting: numeros",
			"expecting: texto",
			"expecting: '.'",
			"expecting: ']'",
			"expecting: texto, '[', EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 0, 0, 3, 3, 0, 0, 4, 5, 6, 7, 4, 0, 7, 8, 0, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
