/* This file was generated by SableCC (http://www.sablecc.org/). */

package SableCC.node;

import SableCC.analysis.*;

@SuppressWarnings("nls")
public final class ADospuntosTexto extends PTexto
{
    private TDospuntos _dospuntos_;

    public ADospuntosTexto()
    {
        // Constructor
    }

    public ADospuntosTexto(
        @SuppressWarnings("hiding") TDospuntos _dospuntos_)
    {
        // Constructor
        setDospuntos(_dospuntos_);

    }

    @Override
    public Object clone()
    {
        return new ADospuntosTexto(
            cloneNode(this._dospuntos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADospuntosTexto(this);
    }

    public TDospuntos getDospuntos()
    {
        return this._dospuntos_;
    }

    public void setDospuntos(TDospuntos node)
    {
        if(this._dospuntos_ != null)
        {
            this._dospuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dospuntos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dospuntos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dospuntos_ == child)
        {
            this._dospuntos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dospuntos_ == oldChild)
        {
            setDospuntos((TDospuntos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
