/* This file was generated by SableCC (http://www.sablecc.org/). */

package SableCC.node;

import SableCC.analysis.*;

@SuppressWarnings("nls")
public final class ALinea extends PLinea
{
    private TAbrecorchete _abrecorchete_;
    private PContenido _contenido_;

    public ALinea()
    {
        // Constructor
    }

    public ALinea(
        @SuppressWarnings("hiding") TAbrecorchete _abrecorchete_,
        @SuppressWarnings("hiding") PContenido _contenido_)
    {
        // Constructor
        setAbrecorchete(_abrecorchete_);

        setContenido(_contenido_);

    }

    @Override
    public Object clone()
    {
        return new ALinea(
            cloneNode(this._abrecorchete_),
            cloneNode(this._contenido_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALinea(this);
    }

    public TAbrecorchete getAbrecorchete()
    {
        return this._abrecorchete_;
    }

    public void setAbrecorchete(TAbrecorchete node)
    {
        if(this._abrecorchete_ != null)
        {
            this._abrecorchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abrecorchete_ = node;
    }

    public PContenido getContenido()
    {
        return this._contenido_;
    }

    public void setContenido(PContenido node)
    {
        if(this._contenido_ != null)
        {
            this._contenido_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._contenido_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abrecorchete_)
            + toString(this._contenido_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abrecorchete_ == child)
        {
            this._abrecorchete_ = null;
            return;
        }

        if(this._contenido_ == child)
        {
            this._contenido_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abrecorchete_ == oldChild)
        {
            setAbrecorchete((TAbrecorchete) newChild);
            return;
        }

        if(this._contenido_ == oldChild)
        {
            setContenido((PContenido) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
