/* This file was generated by SableCC (http://www.sablecc.org/). */

package SableCC.node;

import SableCC.analysis.*;

@SuppressWarnings("nls")
public final class TDospuntos extends Token
{
    public TDospuntos()
    {
        super.setText(":");
    }

    public TDospuntos(int line, int pos)
    {
        super.setText(":");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDospuntos(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDospuntos(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDospuntos text.");
    }
}
