/* This file was generated by SableCC (http://www.sablecc.org/). */

package SableCC.node;

import SableCC.analysis.*;

@SuppressWarnings("nls")
public final class TTextolimitado extends Token
{
    public TTextolimitado(String text)
    {
        setText(text);
    }

    public TTextolimitado(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTextolimitado(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTextolimitado(this);
    }
}
