/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.analysis;

import Lyrics.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAArchivo(AArchivo node);
    void caseALinea(ALinea node);
    void caseATimestampContenido(ATimestampContenido node);
    void caseAMetadatoContenido(AMetadatoContenido node);

    void caseTNumeros(TNumeros node);
    void caseTTexto(TTexto node);
    void caseTTextolimitado(TTextolimitado node);
    void caseTAbrecorchete(TAbrecorchete node);
    void caseTCierracorchete(TCierracorchete node);
    void caseTPunto(TPunto node);
    void caseTDospuntos(TDospuntos node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
