/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.analysis;

import java.util.*;
import Lyrics.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPArchivo().apply(this);
        outStart(node);
    }

    public void inAArchivo(AArchivo node)
    {
        defaultIn(node);
    }

    public void outAArchivo(AArchivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArchivo(AArchivo node)
    {
        inAArchivo(node);
        {
            List<PLinea> copy = new ArrayList<PLinea>(node.getLinea());
            Collections.reverse(copy);
            for(PLinea e : copy)
            {
                e.apply(this);
            }
        }
        outAArchivo(node);
    }

    public void inALinea(ALinea node)
    {
        defaultIn(node);
    }

    public void outALinea(ALinea node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALinea(ALinea node)
    {
        inALinea(node);
        if(node.getContenido() != null)
        {
            node.getContenido().apply(this);
        }
        if(node.getAbrecorchete() != null)
        {
            node.getAbrecorchete().apply(this);
        }
        outALinea(node);
    }

    public void inATimestampContenido(ATimestampContenido node)
    {
        defaultIn(node);
    }

    public void outATimestampContenido(ATimestampContenido node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATimestampContenido(ATimestampContenido node)
    {
        inATimestampContenido(node);
        if(node.getLyric() != null)
        {
            node.getLyric().apply(this);
        }
        if(node.getCierracorchete() != null)
        {
            node.getCierracorchete().apply(this);
        }
        if(node.getMil() != null)
        {
            node.getMil().apply(this);
        }
        if(node.getPunto() != null)
        {
            node.getPunto().apply(this);
        }
        if(node.getSeg() != null)
        {
            node.getSeg().apply(this);
        }
        if(node.getDospuntos() != null)
        {
            node.getDospuntos().apply(this);
        }
        if(node.getMin() != null)
        {
            node.getMin().apply(this);
        }
        outATimestampContenido(node);
    }

    public void inAMetadatoContenido(AMetadatoContenido node)
    {
        defaultIn(node);
    }

    public void outAMetadatoContenido(AMetadatoContenido node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetadatoContenido(AMetadatoContenido node)
    {
        inAMetadatoContenido(node);
        if(node.getCierracorchete() != null)
        {
            node.getCierracorchete().apply(this);
        }
        if(node.getTexto() != null)
        {
            node.getTexto().apply(this);
        }
        if(node.getDospuntos() != null)
        {
            node.getDospuntos().apply(this);
        }
        if(node.getTextolimitado() != null)
        {
            node.getTextolimitado().apply(this);
        }
        outAMetadatoContenido(node);
    }
}
