/* This file was generated by SableCC (http://www.sablecc.org/). */

package SableCC.parser;

import SableCC.node.*;
import SableCC.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTNumeros(@SuppressWarnings("unused") TNumeros node)
    {
        this.index = 0;
    }

    @Override
    public void caseTTextolimitado(@SuppressWarnings("unused") TTextolimitado node)
    {
        this.index = 1;
    }

    @Override
    public void caseTAbrecorchete(@SuppressWarnings("unused") TAbrecorchete node)
    {
        this.index = 2;
    }

    @Override
    public void caseTCierracorchete(@SuppressWarnings("unused") TCierracorchete node)
    {
        this.index = 3;
    }

    @Override
    public void caseTPunto(@SuppressWarnings("unused") TPunto node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDospuntos(@SuppressWarnings("unused") TDospuntos node)
    {
        this.index = 5;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 6;
    }
}
