/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.node;

import Lyrics.analysis.*;

@SuppressWarnings("nls")
public final class AMetadatoContenido extends PContenido
{
    private TTextolimitado _textolimitado_;
    private TDospuntos _dospuntos_;
    private TTexto _texto_;
    private TCierracorchete _cierracorchete_;

    public AMetadatoContenido()
    {
        // Constructor
    }

    public AMetadatoContenido(
        @SuppressWarnings("hiding") TTextolimitado _textolimitado_,
        @SuppressWarnings("hiding") TDospuntos _dospuntos_,
        @SuppressWarnings("hiding") TTexto _texto_,
        @SuppressWarnings("hiding") TCierracorchete _cierracorchete_)
    {
        // Constructor
        setTextolimitado(_textolimitado_);

        setDospuntos(_dospuntos_);

        setTexto(_texto_);

        setCierracorchete(_cierracorchete_);

    }

    @Override
    public Object clone()
    {
        return new AMetadatoContenido(
            cloneNode(this._textolimitado_),
            cloneNode(this._dospuntos_),
            cloneNode(this._texto_),
            cloneNode(this._cierracorchete_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetadatoContenido(this);
    }

    public TTextolimitado getTextolimitado()
    {
        return this._textolimitado_;
    }

    public void setTextolimitado(TTextolimitado node)
    {
        if(this._textolimitado_ != null)
        {
            this._textolimitado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textolimitado_ = node;
    }

    public TDospuntos getDospuntos()
    {
        return this._dospuntos_;
    }

    public void setDospuntos(TDospuntos node)
    {
        if(this._dospuntos_ != null)
        {
            this._dospuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dospuntos_ = node;
    }

    public TTexto getTexto()
    {
        return this._texto_;
    }

    public void setTexto(TTexto node)
    {
        if(this._texto_ != null)
        {
            this._texto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._texto_ = node;
    }

    public TCierracorchete getCierracorchete()
    {
        return this._cierracorchete_;
    }

    public void setCierracorchete(TCierracorchete node)
    {
        if(this._cierracorchete_ != null)
        {
            this._cierracorchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cierracorchete_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._textolimitado_)
            + toString(this._dospuntos_)
            + toString(this._texto_)
            + toString(this._cierracorchete_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._textolimitado_ == child)
        {
            this._textolimitado_ = null;
            return;
        }

        if(this._dospuntos_ == child)
        {
            this._dospuntos_ = null;
            return;
        }

        if(this._texto_ == child)
        {
            this._texto_ = null;
            return;
        }

        if(this._cierracorchete_ == child)
        {
            this._cierracorchete_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._textolimitado_ == oldChild)
        {
            setTextolimitado((TTextolimitado) newChild);
            return;
        }

        if(this._dospuntos_ == oldChild)
        {
            setDospuntos((TDospuntos) newChild);
            return;
        }

        if(this._texto_ == oldChild)
        {
            setTexto((TTexto) newChild);
            return;
        }

        if(this._cierracorchete_ == oldChild)
        {
            setCierracorchete((TCierracorchete) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
