/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.node;

import java.util.*;
import Lyrics.analysis.*;

@SuppressWarnings("nls")
public final class AMetadatoContenido extends PContenido
{
    private TTextolimitado _metadato_;
    private TDospuntos _dospuntos_;
    private final LinkedList<PTexto> _texto_ = new LinkedList<PTexto>();
    private TCierracorchete _cierracorchete_;

    public AMetadatoContenido()
    {
        // Constructor
    }

    public AMetadatoContenido(
        @SuppressWarnings("hiding") TTextolimitado _metadato_,
        @SuppressWarnings("hiding") TDospuntos _dospuntos_,
        @SuppressWarnings("hiding") List<?> _texto_,
        @SuppressWarnings("hiding") TCierracorchete _cierracorchete_)
    {
        // Constructor
        setMetadato(_metadato_);

        setDospuntos(_dospuntos_);

        setTexto(_texto_);

        setCierracorchete(_cierracorchete_);

    }

    @Override
    public Object clone()
    {
        return new AMetadatoContenido(
            cloneNode(this._metadato_),
            cloneNode(this._dospuntos_),
            cloneList(this._texto_),
            cloneNode(this._cierracorchete_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetadatoContenido(this);
    }

    public TTextolimitado getMetadato()
    {
        return this._metadato_;
    }

    public void setMetadato(TTextolimitado node)
    {
        if(this._metadato_ != null)
        {
            this._metadato_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metadato_ = node;
    }

    public TDospuntos getDospuntos()
    {
        return this._dospuntos_;
    }

    public void setDospuntos(TDospuntos node)
    {
        if(this._dospuntos_ != null)
        {
            this._dospuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dospuntos_ = node;
    }

    public LinkedList<PTexto> getTexto()
    {
        return this._texto_;
    }

    public void setTexto(List<?> list)
    {
        for(PTexto e : this._texto_)
        {
            e.parent(null);
        }
        this._texto_.clear();

        for(Object obj_e : list)
        {
            PTexto e = (PTexto) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._texto_.add(e);
        }
    }

    public TCierracorchete getCierracorchete()
    {
        return this._cierracorchete_;
    }

    public void setCierracorchete(TCierracorchete node)
    {
        if(this._cierracorchete_ != null)
        {
            this._cierracorchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cierracorchete_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metadato_)
            + toString(this._dospuntos_)
            + toString(this._texto_)
            + toString(this._cierracorchete_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metadato_ == child)
        {
            this._metadato_ = null;
            return;
        }

        if(this._dospuntos_ == child)
        {
            this._dospuntos_ = null;
            return;
        }

        if(this._texto_.remove(child))
        {
            return;
        }

        if(this._cierracorchete_ == child)
        {
            this._cierracorchete_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._metadato_ == oldChild)
        {
            setMetadato((TTextolimitado) newChild);
            return;
        }

        if(this._dospuntos_ == oldChild)
        {
            setDospuntos((TDospuntos) newChild);
            return;
        }

        for(ListIterator<PTexto> i = this._texto_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTexto) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._cierracorchete_ == oldChild)
        {
            setCierracorchete((TCierracorchete) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
