/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.node;

import Lyrics.analysis.*;

@SuppressWarnings("nls")
public final class APuntoTexto extends PTexto
{
    private TPunto _punto_;

    public APuntoTexto()
    {
        // Constructor
    }

    public APuntoTexto(
        @SuppressWarnings("hiding") TPunto _punto_)
    {
        // Constructor
        setPunto(_punto_);

    }

    @Override
    public Object clone()
    {
        return new APuntoTexto(
            cloneNode(this._punto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPuntoTexto(this);
    }

    public TPunto getPunto()
    {
        return this._punto_;
    }

    public void setPunto(TPunto node)
    {
        if(this._punto_ != null)
        {
            this._punto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._punto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._punto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._punto_ == child)
        {
            this._punto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._punto_ == oldChild)
        {
            setPunto((TPunto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
