/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.node;

import Lyrics.analysis.*;

@SuppressWarnings("nls")
public final class AStringTexto extends PTexto
{
    private TTextolimitado _textolimitado_;

    public AStringTexto()
    {
        // Constructor
    }

    public AStringTexto(
        @SuppressWarnings("hiding") TTextolimitado _textolimitado_)
    {
        // Constructor
        setTextolimitado(_textolimitado_);

    }

    @Override
    public Object clone()
    {
        return new AStringTexto(
            cloneNode(this._textolimitado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringTexto(this);
    }

    public TTextolimitado getTextolimitado()
    {
        return this._textolimitado_;
    }

    public void setTextolimitado(TTextolimitado node)
    {
        if(this._textolimitado_ != null)
        {
            this._textolimitado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textolimitado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._textolimitado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._textolimitado_ == child)
        {
            this._textolimitado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._textolimitado_ == oldChild)
        {
            setTextolimitado((TTextolimitado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
