/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.node;

import java.util.*;
import Lyrics.analysis.*;

@SuppressWarnings("nls")
public final class ATimestampContenido extends PContenido
{
    private TNumeros _min_;
    private TDospuntos _dospuntos_;
    private TNumeros _seg_;
    private TPunto _punto_;
    private TNumeros _mil_;
    private TCierracorchete _cierracorchete_;
    private final LinkedList<PTexto> _lyric_ = new LinkedList<PTexto>();

    public ATimestampContenido()
    {
        // Constructor
    }

    public ATimestampContenido(
        @SuppressWarnings("hiding") TNumeros _min_,
        @SuppressWarnings("hiding") TDospuntos _dospuntos_,
        @SuppressWarnings("hiding") TNumeros _seg_,
        @SuppressWarnings("hiding") TPunto _punto_,
        @SuppressWarnings("hiding") TNumeros _mil_,
        @SuppressWarnings("hiding") TCierracorchete _cierracorchete_,
        @SuppressWarnings("hiding") List<?> _lyric_)
    {
        // Constructor
        setMin(_min_);

        setDospuntos(_dospuntos_);

        setSeg(_seg_);

        setPunto(_punto_);

        setMil(_mil_);

        setCierracorchete(_cierracorchete_);

        setLyric(_lyric_);

    }

    @Override
    public Object clone()
    {
        return new ATimestampContenido(
            cloneNode(this._min_),
            cloneNode(this._dospuntos_),
            cloneNode(this._seg_),
            cloneNode(this._punto_),
            cloneNode(this._mil_),
            cloneNode(this._cierracorchete_),
            cloneList(this._lyric_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimestampContenido(this);
    }

    public TNumeros getMin()
    {
        return this._min_;
    }

    public void setMin(TNumeros node)
    {
        if(this._min_ != null)
        {
            this._min_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._min_ = node;
    }

    public TDospuntos getDospuntos()
    {
        return this._dospuntos_;
    }

    public void setDospuntos(TDospuntos node)
    {
        if(this._dospuntos_ != null)
        {
            this._dospuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dospuntos_ = node;
    }

    public TNumeros getSeg()
    {
        return this._seg_;
    }

    public void setSeg(TNumeros node)
    {
        if(this._seg_ != null)
        {
            this._seg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seg_ = node;
    }

    public TPunto getPunto()
    {
        return this._punto_;
    }

    public void setPunto(TPunto node)
    {
        if(this._punto_ != null)
        {
            this._punto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._punto_ = node;
    }

    public TNumeros getMil()
    {
        return this._mil_;
    }

    public void setMil(TNumeros node)
    {
        if(this._mil_ != null)
        {
            this._mil_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mil_ = node;
    }

    public TCierracorchete getCierracorchete()
    {
        return this._cierracorchete_;
    }

    public void setCierracorchete(TCierracorchete node)
    {
        if(this._cierracorchete_ != null)
        {
            this._cierracorchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cierracorchete_ = node;
    }

    public LinkedList<PTexto> getLyric()
    {
        return this._lyric_;
    }

    public void setLyric(List<?> list)
    {
        for(PTexto e : this._lyric_)
        {
            e.parent(null);
        }
        this._lyric_.clear();

        for(Object obj_e : list)
        {
            PTexto e = (PTexto) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._lyric_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._min_)
            + toString(this._dospuntos_)
            + toString(this._seg_)
            + toString(this._punto_)
            + toString(this._mil_)
            + toString(this._cierracorchete_)
            + toString(this._lyric_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._min_ == child)
        {
            this._min_ = null;
            return;
        }

        if(this._dospuntos_ == child)
        {
            this._dospuntos_ = null;
            return;
        }

        if(this._seg_ == child)
        {
            this._seg_ = null;
            return;
        }

        if(this._punto_ == child)
        {
            this._punto_ = null;
            return;
        }

        if(this._mil_ == child)
        {
            this._mil_ = null;
            return;
        }

        if(this._cierracorchete_ == child)
        {
            this._cierracorchete_ = null;
            return;
        }

        if(this._lyric_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._min_ == oldChild)
        {
            setMin((TNumeros) newChild);
            return;
        }

        if(this._dospuntos_ == oldChild)
        {
            setDospuntos((TDospuntos) newChild);
            return;
        }

        if(this._seg_ == oldChild)
        {
            setSeg((TNumeros) newChild);
            return;
        }

        if(this._punto_ == oldChild)
        {
            setPunto((TPunto) newChild);
            return;
        }

        if(this._mil_ == oldChild)
        {
            setMil((TNumeros) newChild);
            return;
        }

        if(this._cierracorchete_ == oldChild)
        {
            setCierracorchete((TCierracorchete) newChild);
            return;
        }

        for(ListIterator<PTexto> i = this._lyric_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTexto) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
