/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.node;

import Lyrics.analysis.*;

@SuppressWarnings("nls")
public final class TAbrecorchete extends Token
{
    public TAbrecorchete()
    {
        super.setText("[");
    }

    public TAbrecorchete(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAbrecorchete(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAbrecorchete(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAbrecorchete text.");
    }
}
