/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lyrics.node;

import Lyrics.analysis.*;

@SuppressWarnings("nls")
public final class TCierracorchete extends Token
{
    public TCierracorchete()
    {
        super.setText("]");
    }

    public TCierracorchete(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCierracorchete(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCierracorchete(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCierracorchete text.");
    }
}
