/* This file was generated by SableCC (http://www.sablecc.org/). */

package SableCC.analysis;

import java.util.*;
import SableCC.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArchivo(AArchivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALinea(ALinea node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATimestampContenido(ATimestampContenido node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMetadatoContenido(AMetadatoContenido node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringTexto(AStringTexto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroTexto(ANumeroTexto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPuntoTexto(APuntoTexto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADospuntosTexto(ADospuntosTexto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeros(TNumeros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTextolimitado(TTextolimitado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAbrecorchete(TAbrecorchete node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCierracorchete(TCierracorchete node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPunto(TPunto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDospuntos(TDospuntos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
