/* This file was generated by SableCC (http://www.sablecc.org/). */

package SableCC.analysis;

import java.util.*;
import SableCC.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPArchivo().apply(this);
        outStart(node);
    }

    public void inAArchivo(AArchivo node)
    {
        defaultIn(node);
    }

    public void outAArchivo(AArchivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArchivo(AArchivo node)
    {
        inAArchivo(node);
        {
            List<PLinea> copy = new ArrayList<PLinea>(node.getLinea());
            Collections.reverse(copy);
            for(PLinea e : copy)
            {
                e.apply(this);
            }
        }
        outAArchivo(node);
    }

    public void inALinea(ALinea node)
    {
        defaultIn(node);
    }

    public void outALinea(ALinea node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALinea(ALinea node)
    {
        inALinea(node);
        if(node.getContenido() != null)
        {
            node.getContenido().apply(this);
        }
        if(node.getAbrecorchete() != null)
        {
            node.getAbrecorchete().apply(this);
        }
        outALinea(node);
    }

    public void inATimestampContenido(ATimestampContenido node)
    {
        defaultIn(node);
    }

    public void outATimestampContenido(ATimestampContenido node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATimestampContenido(ATimestampContenido node)
    {
        inATimestampContenido(node);
        {
            List<PTexto> copy = new ArrayList<PTexto>(node.getLyric());
            Collections.reverse(copy);
            for(PTexto e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCierracorchete() != null)
        {
            node.getCierracorchete().apply(this);
        }
        if(node.getMil() != null)
        {
            node.getMil().apply(this);
        }
        if(node.getPunto() != null)
        {
            node.getPunto().apply(this);
        }
        if(node.getSeg() != null)
        {
            node.getSeg().apply(this);
        }
        if(node.getDospuntos() != null)
        {
            node.getDospuntos().apply(this);
        }
        if(node.getMin() != null)
        {
            node.getMin().apply(this);
        }
        outATimestampContenido(node);
    }

    public void inAMetadatoContenido(AMetadatoContenido node)
    {
        defaultIn(node);
    }

    public void outAMetadatoContenido(AMetadatoContenido node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetadatoContenido(AMetadatoContenido node)
    {
        inAMetadatoContenido(node);
        if(node.getCierracorchete() != null)
        {
            node.getCierracorchete().apply(this);
        }
        {
            List<PTexto> copy = new ArrayList<PTexto>(node.getTexto());
            Collections.reverse(copy);
            for(PTexto e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDospuntos() != null)
        {
            node.getDospuntos().apply(this);
        }
        if(node.getMetadato() != null)
        {
            node.getMetadato().apply(this);
        }
        outAMetadatoContenido(node);
    }

    public void inAStringTexto(AStringTexto node)
    {
        defaultIn(node);
    }

    public void outAStringTexto(AStringTexto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringTexto(AStringTexto node)
    {
        inAStringTexto(node);
        if(node.getTextolimitado() != null)
        {
            node.getTextolimitado().apply(this);
        }
        outAStringTexto(node);
    }

    public void inANumeroTexto(ANumeroTexto node)
    {
        defaultIn(node);
    }

    public void outANumeroTexto(ANumeroTexto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroTexto(ANumeroTexto node)
    {
        inANumeroTexto(node);
        if(node.getNumeros() != null)
        {
            node.getNumeros().apply(this);
        }
        outANumeroTexto(node);
    }

    public void inAPuntoTexto(APuntoTexto node)
    {
        defaultIn(node);
    }

    public void outAPuntoTexto(APuntoTexto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPuntoTexto(APuntoTexto node)
    {
        inAPuntoTexto(node);
        if(node.getPunto() != null)
        {
            node.getPunto().apply(this);
        }
        outAPuntoTexto(node);
    }

    public void inADospuntosTexto(ADospuntosTexto node)
    {
        defaultIn(node);
    }

    public void outADospuntosTexto(ADospuntosTexto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADospuntosTexto(ADospuntosTexto node)
    {
        inADospuntosTexto(node);
        if(node.getDospuntos() != null)
        {
            node.getDospuntos().apply(this);
        }
        outADospuntosTexto(node);
    }
}
